apiVersion: v1
kind: Service
metadata:
  name: {{ include "databunker-demo.fullname" . }}
  labels:
    {{- include "databunker-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if contains "NodePort" .Values.service.type }}
      nodePort: 30300
{{- end }}
  selector:
    {{- include "databunker-demo.selectorLabels" . | nindent 4 }}
