name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run golint
      run: |
        apt install golint
        cd src
        golint
        echo done
