name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Run golint
      run: |
        go version
        sudo apt install -y golint
        cd src
        golint
        cd ..
        echo done
    - name: Download deps
      run: |
        sudo apt install -y golang
        cd src
        go get -d -v
        echo done
    - name: Run go vet
      run: |
        sudo apt install -y golang
        cd src
        go vet
        echo done
    - name: Run go test
      run: |
        sudo apt install -y golang
        cd src
        go test
        echo done
